### ISSUE TITLE
Texture for WD Ship Core for Jumping/Cooldown Missing

### ISSUE THREAD

**Issue by DaBossWade** [StargateMC/Project#20]
The texture for the ship core is missing when you are jumping and when it is cooling down.
![2017-06-29_00 02 48](https://user-images.githubusercontent.com/29767542/27670980-b19ffec0-5c5e-11e7-8202-6832f020bd05.png)
![2017-06-29_00 03 01](https://user-images.githubusercontent.com/29767542/27670979-b19fb398-5c5e-11e7-8d67-0b6bb24185ad.png)

**Comment by Bysokar** [comment]
This is a known issue with WarpDrive and will be resolved when WarpDrive is publically released.
Closing as theres nothing  I can do about it :)
