### ISSUE TITLE
Warp Drive: Stained Hull can't be destroy

### ISSUE THREAD

**Issue by Elanis** [StargateMC/Project#25]
When we destroy a stained advanced hull, it drops the block but not destroy it, it infinite drop the block.

We tried diamond pickaxe and Atomic Disassembler to destroy it.

**Comment by Bysokar** [comment]
@lemadec - Looks like this might be one for you :)

**Comment by Elanis** [comment]
Same bug with stained basic hull

**Comment by LemADEC** [comment]
already fixed in dev

**Comment by Bysokar** [comment]
Thx @lemadec

**Comment by Elanis** [comment]
Cool ;D Thanks @LemADEC
