### ISSUE TITLE
Pneumatic Craft Global Variables do not work

### ISSUE THREAD

**Issue by DaBossWade** [StargateMC/Project#30]
When ever I try to program the remote to control a drone for me, global variables do not work.
![2017-07-18_00 07 24](https://user-images.githubusercontent.com/29767542/28300411-4f33e104-6b4d-11e7-9f0d-8a5d60b2fc09.png)
![2017-07-18_00 07 27](https://user-images.githubusercontent.com/29767542/28300437-721cdf72-6b4d-11e7-80f8-2177b9ed2244.png)
![2017-07-18_00 09 16](https://user-images.githubusercontent.com/29767542/28300441-76ca1ad0-6b4d-11e7-942d-d0bec14125c9.png)
![2017-07-18_00 07 43](https://user-images.githubusercontent.com/29767542/28300446-7b46a0ce-6b4d-11e7-9dcf-dccb869aa6d6.png)
![2017-07-18_00 09 26](https://user-images.githubusercontent.com/29767542/28300449-7e4a1468-6b4d-11e7-9682-d738df75a55b.png)
![2017-07-18_00 07 49](https://user-images.githubusercontent.com/29767542/28300451-80e9a4e0-6b4d-11e7-9bf7-683c99acfabc.png)
The screenshot shows me changing the global variable "#1" to be 0,2,0 and 0,-2,0. But does not change the drones name, which is a counter for "#1".

**Comment by Bysokar** [comment]
This belongs on the Pneumaticcraft github.

**Comment by Bysokar** [comment]
https://github.com/MineMaarten/PneumaticCraft
