### ISSUE TITLE
AE2 quantumbridge deleted

### ISSUE THREAD

**Issue by nosknut** [StargateMC/Project#39]
Plz put it back into the game as i cannot find it in NEI

**Comment by Bysokar** [comment]
No... item and energy transfers over unlimited distance are not allowed. I may revisit this later.

**Comment by nosknut** [comment]
It dossent need to be infinite
 I want it for making a more organized base
Having a qbridge is easyer to maintain and troubbleshoot than cables

**Comment by nosknut** [comment]
64-100blocks would be fine

**Comment by Bysokar** [comment]
A black hole is not something you use to clean up cabling..... even if I reenable this it will only work between worlds... sorry.
